relative_urls: false
remove_script_host: false
width: 100%
height: 500px
menubar: false
toolbar1: styleselect | bold italic underline | bullist numlist | undo redo | link uploadimage | code
plugins:
  - table
  - fullscreen
  - link
  - uploadimage
  - code
