width : 700px
toolbar1: styleselect | bold italic underline | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | undo redo | link uploadimage
plugins:
  - table
  - fullscreen
  - link
  - uploadimage
