relative_urls: false
remove_script_host: false
width: 700px
toolbar1: styleselect | code | bold italic underline | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | undo redo | link uploadimage
plugins:
  - table
  - fullscreen
  - link
  - uploadimage
  - code
